// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: prices.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPricebyID = `-- name: GetPricebyID :one
SELECT Price
FROM Prices
WHERE Item_id = $1
`

func (q *Queries) GetPricebyID(ctx context.Context, itemID uuid.UUID) (float64, error) {
	row := q.db.QueryRowContext(ctx, getPricebyID, itemID)
	var price float64
	err := row.Scan(&price)
	return price, err
}
